language: php

php: ["5.3", "5.4", "5.5", "hhvm"]

matrix:
  allow_failures:
    - php: hhvm

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.5
    - secure: "QzUu6clBTnNTt5oW1JXiXcNUBqfZyVKqCMbIKEXzX0gqEGYUnuBkzVwmWgoux5NhYUDk2LF88X7JdZsyu7WXKr72J5WF5t3/IpPzI+kNk6v5DeJeUptQL/fF5PDNkpJmqkmSm9bXXCK+nS1DO3pYLij6hj4bfkJQhoHp7naa4PI="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
