language: php

php: ["5.3", "5.4", "5.5", "hhvm"]

matrix:
  allow_failures:
    - php: hhvm

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.5
    - secure: "DwYkRO60s/APnbp20ghKZ2mN5tU2IbZ7Bf96Vdl5ghfHxKiR+lplpW8ykvt/MqVGNef8YUBxCB2PgVGTC22cAscyLQopp2f7ZJU4tDdTJTsFDZOLPTVVvx4rYRrXObBn7YZNWfd5DhGz1F7SayinU6Qv3rO6seRzN2TxN51kZtU="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
